from __future__ import annotations

APPLICATION_DISPLAY_NAME = "DIGITAL GEOLOG GASRATIO&PIXLER"
APPLICATION_PRODUCT_LINE = "DIGITAL GEOLOG"
APPLICATION_SUITE_NAME = "GASRATIO&PIXLER"
REPORT_BRAND_WORDMARK = APPLICATION_DISPLAY_NAME
DIAGNOSTIC_BUNDLE_PREFIX = "DIGITAL_GEOLOG_diagnostics"

__all__ = [
    "APPLICATION_DISPLAY_NAME",
    "APPLICATION_PRODUCT_LINE",
    "APPLICATION_SUITE_NAME",
    "REPORT_BRAND_WORDMARK",
    "DIAGNOSTIC_BUNDLE_PREFIX",
]
