from __future__ import annotations

PRODUCT_NAME = "DIGITAL GEOLOG GASRATIO&PIXLER"
PRODUCT_FAMILY_NAME = "DIGITAL GEOLOG"
PRODUCT_SUITE_NAME = "GASRATIO&PIXLER"

__all__ = ["PRODUCT_NAME", "PRODUCT_FAMILY_NAME", "PRODUCT_SUITE_NAME"]
