from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import stat

from PySide6.QtCore import QStandardPaths


PRINT_ARTIFACT_MARKER_SCHEMA_VERSION = 1
PRINT_ARTIFACT_MARKER_NAME = ".geolog-print-artifacts.json"
PRINT_ARTIFACT_OWNER = "geolog-gasratio-pixler/legacy-physical-print-copies"

_LEGACY_COPY_NAME = re.compile(
    r"^.+_[0-9]{8}_[0-9]{6}_[0-9]{6}\.pdf$",
    re.IGNORECASE,
)
_LEGACY_COPY_TEMP_NAME = re.compile(
    r"^\..+_[0-9]{8}_[0-9]{6}_[0-9]{6}\.pdf\.[a-z0-9_]{8}\.tmp$",
    re.IGNORECASE,
)


@dataclass(frozen=True, slots=True)
class PrintArtifactCleanupResult:
    scanned_files: int = 0
    deleted_files: int = 0
    freed_bytes: int = 0
    failed_files: int = 0
    skipped_reason: str | None = None


def legacy_physical_print_directory() -> Path:
    documents = QStandardPaths.writableLocation(
        QStandardPaths.StandardLocation.DocumentsLocation
    )
    root = Path(documents) if documents else Path.home() / "Documents"
    return root / "GEOLOG GASRATIO Pixler" / "Печатные копии"


def cleanup_legacy_physical_print_copies(
    root: str | Path | None = None,
) -> PrintArtifactCleanupResult:
    """Remove only obsolete PDF copies generated by old printer jobs.

    Older releases rendered a timestamped PDF before every preview refresh and
    physical print.  The renderer no longer needs those copies.  Cleanup fails
    closed unless the dedicated directory either has a valid ownership marker
    or contains only files with the exact legacy-generated name contract.
    """

    directory = Path(root) if root is not None else legacy_physical_print_directory()
    if not directory.exists():
        return PrintArtifactCleanupResult()
    if not directory.is_dir() or _is_reparse_point(directory):
        return PrintArtifactCleanupResult(skipped_reason="unsafe_root")

    marker = directory / PRINT_ARTIFACT_MARKER_NAME
    if marker.exists():
        marker_reason = _validate_marker(marker, directory)
        if marker_reason is not None:
            return PrintArtifactCleanupResult(skipped_reason=marker_reason)
    else:
        adoption_reason = _safe_legacy_directory_reason(directory)
        if adoption_reason is not None:
            return PrintArtifactCleanupResult(skipped_reason=adoption_reason)
        _write_marker(marker, directory)

    candidates = tuple(path for path in directory.iterdir() if _is_legacy_artifact(path))
    deleted = 0
    freed = 0
    failed = 0
    for path in candidates:
        try:
            size = path.stat().st_size
            path.unlink()
            deleted += 1
            freed += size
        except OSError:
            failed += 1
    return PrintArtifactCleanupResult(
        scanned_files=len(candidates),
        deleted_files=deleted,
        freed_bytes=freed,
        failed_files=failed,
    )


def _safe_legacy_directory_reason(directory: Path) -> str | None:
    for path in directory.iterdir():
        if not _is_legacy_artifact(path):
            return "unowned_contents"
    return None


def _is_legacy_artifact(path: Path) -> bool:
    return (
        (
            _LEGACY_COPY_NAME.fullmatch(path.name) is not None
            or _LEGACY_COPY_TEMP_NAME.fullmatch(path.name) is not None
        )
        and path.is_file()
        and not _is_reparse_point(path)
    )


def _write_marker(marker: Path, directory: Path) -> None:
    payload = {
        "schema_version": PRINT_ARTIFACT_MARKER_SCHEMA_VERSION,
        "owner": PRINT_ARTIFACT_OWNER,
        "root": str(directory.resolve()),
    }
    temporary = marker.with_name(marker.name + ".tmp")
    try:
        temporary.write_text(
            json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
            + "\n",
            encoding="utf-8",
        )
        os.replace(temporary, marker)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def _validate_marker(marker: Path, directory: Path) -> str | None:
    if not marker.is_file() or _is_reparse_point(marker):
        return "invalid_marker"
    try:
        payload = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return "invalid_marker"
    if not isinstance(payload, dict):
        return "invalid_marker"
    if (
        payload.get("schema_version") != PRINT_ARTIFACT_MARKER_SCHEMA_VERSION
        or payload.get("owner") != PRINT_ARTIFACT_OWNER
        or payload.get("root") != str(directory.resolve())
    ):
        return "marker_owner_mismatch"
    return None


def _is_reparse_point(path: Path) -> bool:
    try:
        details = path.lstat()
    except OSError:
        return True
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
    attributes = getattr(details, "st_file_attributes", 0)
    return path.is_symlink() or bool(reparse_flag and attributes & reparse_flag)
