from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass

from geoworkbench.domain.models import (
    MasterlogColumnTemplate,
    MasterlogCurveStyle,
    MasterlogHeaderElement,
    MasterlogTemplate,
)
from geoworkbench.services.localization import AppLanguage


@dataclass(frozen=True, slots=True)
class MasterlogFormPreset:
    preset_id: str
    names: dict[AppLanguage, str]
    descriptions: dict[AppLanguage, str]
    template: MasterlogTemplate

    def name(self, language: AppLanguage) -> str:
        return self.names[language]

    def description(self, language: AppLanguage) -> str:
        return self.descriptions[language]


@dataclass(frozen=True, slots=True)
class MasterlogHeaderPreset:
    preset_id: str
    names: dict[AppLanguage, str]
    descriptions: dict[AppLanguage, str]
    height_mm: float
    elements: tuple[MasterlogHeaderElement, ...]
    preferred_orientation: str = "both"

    def name(self, language: AppLanguage) -> str:
        return self.names[language]

    def description(self, language: AppLanguage) -> str:
        return self.descriptions[language]


def _texts(ru: str, kk: str, en: str) -> dict[AppLanguage, str]:
    return {AppLanguage.RU: ru, AppLanguage.KK: kk, AppLanguage.EN: en}


def _element(
    element_id: str,
    element_type: str,
    x: float,
    y: float,
    width_mm: float,
    height_mm: float,
    **properties: object,
) -> MasterlogHeaderElement:
    return MasterlogHeaderElement(element_id, element_type, x, y, width_mm, height_mm, properties)


STANDARD_HEADER = MasterlogHeaderPreset(
    "project_well",
    _texts("Проект и скважина", "Жоба және ұңғыма", "Project and well"),
    _texts(
        "Универсальная редактируемая шапка с реквизитами проекта и подрядчика.",
        "Жоба мен мердігер деректемелері бар өңделетін әмбебап тақырып.",
        "Editable general header with project and contractor details.",
    ),
    42.0,
    (
        _element(
            "title", "text", 5, 3, 200, 8, text="MASTERLOG", font_size_mm=6.0, color="#0f172a"
        ),
        _element(
            "project_label",
            "text",
            5,
            14,
            25,
            6,
            text="Project:",
            font_size_mm=3.2,
            color="#334155",
        ),
        _element(
            "project",
            "field",
            30,
            14,
            70,
            6,
            field="project.name",
            font_size_mm=3.5,
            color="#0f172a",
        ),
        _element(
            "well_label", "text", 105, 14, 20, 6, text="Well:", font_size_mm=3.2, color="#334155"
        ),
        _element(
            "well", "field", 125, 14, 80, 6, field="well.name", font_size_mm=3.5, color="#0f172a"
        ),
        _element(
            "dataset_label",
            "text",
            5,
            23,
            25,
            6,
            text="Dataset:",
            font_size_mm=3.2,
            color="#334155",
        ),
        _element(
            "dataset",
            "field",
            30,
            23,
            70,
            6,
            field="dataset.name",
            font_size_mm=3.5,
            color="#0f172a",
        ),
        _element(
            "operator",
            "text",
            105,
            23,
            48,
            6,
            text="Operator: [edit]",
            font_size_mm=3.2,
            color="#334155",
        ),
        _element(
            "contractor",
            "text",
            155,
            23,
            50,
            6,
            text="Contractor: [edit]",
            font_size_mm=3.2,
            color="#334155",
        ),
        _element("separator", "line", 5, 34, 200, 0.1, color="#334155", width=0.6),
    ),
)

LITHOLOGY_HEADER = MasterlogHeaderPreset(
    "project_well_lithology",
    _texts(
        "Проект, скважина и литология",
        "Жоба, ұңғыма және литология",
        "Project, well and lithology",
    ),
    _texts(
        "Расширенная шапка с автоматически формируемой литологической легендой.",
        "Автоматты литологиялық шартты белгілері бар кеңейтілген тақырып.",
        "Extended header with an automatically generated lithology legend.",
    ),
    60.0,
    tuple(deepcopy(STANDARD_HEADER.elements))
    + (
        _element(
            "lithology_legend",
            "lithology_legend",
            5,
            35,
            200,
            22,
            scope="all",
            columns=5,
            show_code=True,
            font_size_mm=2.6,
        ),
    ),
)

GEOLOGICAL_GEOCHEMICAL_HEADER = MasterlogHeaderPreset(
    "geological_geochemical",
    _texts(
        "Геолого-геохимический Masterlog",
        "Геологиялық-геохимиялық Masterlog",
        "Geological-geochemical Masterlog",
    ),
    _texts(
        "Редактируемая шапка по переданному эталону: реквизиты скважины, легенды, конструкция и исполнители.",
        "Берілген эталон бойынша өңделетін тақырып: ұңғыма деректері, шартты белгілер, конструкция және орындаушылар.",
        "Editable reference-based header with well metadata, legends, construction and personnel.",
    ),
    110.0,
    (
        _element(
            "geo_title",
            "text",
            92,
            2,
            155,
            10,
            text="МАСТЕРЛОГ",
            font_size_mm=6.2,
            color="#0f172a",
            bold=True,
            alignment="center",
            frame=True,
        ),
        _element(
            "geo_country_label",
            "text",
            5,
            3,
            28,
            5,
            text="СТРАНА",
            font_size_mm=2.4,
            color="#334155",
            bold=True,
        ),
        _element(
            "geo_country",
            "field",
            34,
            3,
            52,
            5,
            field="header.country",
            font_size_mm=2.8,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_customer_label",
            "text",
            252,
            3,
            30,
            5,
            text="ЗАКАЗЧИК",
            font_size_mm=2.4,
            color="#334155",
            bold=True,
        ),
        _element(
            "geo_customer",
            "field",
            282,
            3,
            52,
            5,
            field="header.customer",
            font_size_mm=2.6,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_field_label",
            "text",
            5,
            10,
            28,
            5,
            text="Месторождение",
            font_size_mm=2.3,
            color="#334155",
        ),
        _element(
            "geo_field",
            "field",
            34,
            10,
            52,
            5,
            field="header.field",
            font_size_mm=2.7,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_well_label",
            "text",
            5,
            17,
            28,
            5,
            text="СКВАЖИНА",
            font_size_mm=2.4,
            color="#334155",
            bold=True,
        ),
        _element(
            "geo_well",
            "field",
            34,
            17,
            52,
            5,
            field="header.well_number",
            font_size_mm=3.0,
            color="#0f172a",
            bold=True,
            frame=True,
        ),
        _element(
            "geo_interval_label",
            "text",
            5,
            24,
            28,
            5,
            text="Интервал",
            font_size_mm=2.3,
            color="#334155",
        ),
        _element(
            "geo_interval",
            "field",
            34,
            24,
            52,
            5,
            field="header.interval",
            font_size_mm=2.7,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_scale_label",
            "text",
            5,
            31,
            28,
            5,
            text="Масштаб",
            font_size_mm=2.3,
            color="#334155",
        ),
        _element(
            "geo_scale",
            "field",
            34,
            31,
            52,
            5,
            field="header.scale",
            font_size_mm=2.7,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_project_label",
            "text",
            92,
            14,
            30,
            5,
            text="Проект",
            font_size_mm=2.3,
            color="#334155",
        ),
        _element(
            "geo_project",
            "field",
            122,
            14,
            60,
            5,
            field="project.name",
            font_size_mm=2.7,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_dataset_label",
            "text",
            184,
            14,
            26,
            5,
            text="Набор",
            font_size_mm=2.3,
            color="#334155",
        ),
        _element(
            "geo_dataset",
            "field",
            210,
            14,
            37,
            5,
            field="dataset.name",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_contractor_label",
            "text",
            92,
            21,
            30,
            5,
            text="Исполнитель",
            font_size_mm=2.3,
            color="#334155",
        ),
        _element(
            "geo_contractor",
            "field",
            122,
            21,
            125,
            5,
            field="header.contractor",
            font_size_mm=2.6,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_driller_label",
            "text",
            92,
            28,
            30,
            5,
            text="Буровая компания",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_driller",
            "field",
            122,
            28,
            125,
            5,
            field="header.drilling_company",
            font_size_mm=2.6,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_engineers_label",
            "text",
            92,
            35,
            30,
            5,
            text="Инженеры / геологи",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_engineers",
            "field",
            122,
            35,
            125,
            8,
            field="header.engineers",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_actual_label",
            "text",
            252,
            10,
            38,
            5,
            text="Фактическая глубина",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_actual",
            "field",
            290,
            10,
            44,
            5,
            field="header.actual_depth",
            font_size_mm=2.7,
            color="#0f172a",
            frame=True,
            alignment="center",
        ),
        _element(
            "geo_project_depth_label",
            "text",
            252,
            17,
            38,
            5,
            text="Проектная глубина",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_project_depth",
            "field",
            290,
            17,
            44,
            5,
            field="header.project_depth",
            font_size_mm=2.7,
            color="#0f172a",
            frame=True,
            alignment="center",
        ),
        _element(
            "geo_start_label",
            "text",
            252,
            24,
            38,
            5,
            text="Начало бурения",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_start",
            "field",
            290,
            24,
            44,
            5,
            field="header.start_date",
            font_size_mm=2.6,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_end_label",
            "text",
            252,
            31,
            38,
            5,
            text="Конец бурения",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_end",
            "field",
            290,
            31,
            44,
            5,
            field="header.end_date",
            font_size_mm=2.6,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_lat_label",
            "text",
            252,
            38,
            18,
            5,
            text="Широта",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_lat",
            "field",
            270,
            38,
            64,
            5,
            field="header.latitude",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_lon_label",
            "text",
            252,
            45,
            18,
            5,
            text="Долгота",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_lon",
            "field",
            270,
            45,
            64,
            5,
            field="header.longitude",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_rig_floor_label",
            "text",
            5,
            38,
            28,
            5,
            text="Высота ротора",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_rig_floor",
            "field",
            34,
            38,
            52,
            5,
            field="header.rig_floor",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_altitude_label",
            "text",
            5,
            45,
            28,
            5,
            text="Альтитуда устья",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_altitude",
            "field",
            34,
            45,
            52,
            5,
            field="header.wellhead_altitude",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_well_type_label",
            "text",
            92,
            45,
            30,
            5,
            text="Вид скважины",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_well_type",
            "field",
            122,
            45,
            58,
            5,
            field="header.well_type",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_rig_label",
            "text",
            182,
            45,
            24,
            5,
            text="Буровая",
            font_size_mm=2.2,
            color="#334155",
        ),
        _element(
            "geo_rig",
            "field",
            206,
            45,
            41,
            5,
            field="header.rig",
            font_size_mm=2.5,
            color="#0f172a",
            frame=True,
        ),
        _element("geo_separator", "line", 5, 53, 329, 0.1, color="#334155", width=0.5),
        _element(
            "geo_lithology_legend",
            "lithology_legend",
            5,
            56,
            148,
            49,
            scope="all",
            columns=4,
            show_code=True,
            font_size_mm=2.05,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_lba_legend",
            "lba_legend",
            156,
            56,
            74,
            49,
            font_size_mm=1.95,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "geo_hc_legend",
            "text",
            233,
            56,
            48,
            49,
            text="УСЛОВНЫЕ ОБОЗНАЧЕНИЯ\n● Фоновый газ\n◆ Газ пластовый\n▲ Газ СПО\n■ Газ-тест\n○ Нефтепроявление\n◉ Нефтенасыщенность\n✦ Керн с признаками УВ",
            font_size_mm=1.95,
            color="#0f172a",
            bold=True,
            frame=True,
        ),
        _element(
            "geo_construction",
            "field",
            284,
            56,
            50,
            49,
            field="header.well_construction",
            font_size_mm=1.9,
            color="#0f172a",
            frame=True,
            alignment="left",
        ),
    ),
)


KAZGEOLOGY_REFERENCE_HEADER = MasterlogHeaderPreset(
    "kazgeology_blank",
    _texts(
        "МАСТЕРЛОГ — эталонная шапка по образцу",
        "МАСТЕРЛОГ — үлгі бойынша эталондық тақырып",
        "MASTERLOG — reference header from the supplied example",
    ),
    _texts(
        "Готовая шапка по переданному образцу с двумя загружаемыми логотипами, реквизитами скважины, легендами и конструкцией.",
        "Берілген үлгі бойынша екі жүктелетін логотипі, ұңғыма деректері, шартты белгілері және конструкциясы бар дайын тақырып.",
        "Reference-ready header with two uploadable logo slots, well metadata, legends and construction.",
    ),
    104.0,
    (
        _element(
            "kz_logo_left",
            "image",
            5,
            3,
            45,
            18,
            optional=True,
            logo_role="contractor",
            mode="fit",
            opacity=1.0,
            frame=True,
            frame_color="#64748b",
            background="#f8fafc",
            placeholder_text_ru="Загрузить логотип исполнителя",
            placeholder_text_kk="Орындаушы логотипін жүктеу",
            placeholder_text_en="Load contractor logo",
            placeholder_font_size_mm=2.2,
        ),
        _element(
            "kz_main_title",
            "text",
            53,
            3,
            278,
            9,
            text="ГЕОЛОГО-ТЕХНОЛОГИЧЕСКИЕ ИССЛЕДОВАНИЯ",
            font_size_mm=5.0,
            color="#0f172a",
            bold=True,
            alignment="center",
            frame=True,
            background="#ffffff",
        ),
        _element(
            "kz_subtitle",
            "text",
            53,
            13,
            278,
            8,
            text="МАСТЕРЛОГ",
            font_size_mm=4.0,
            color="#0f172a",
            bold=True,
            alignment="center",
            frame=True,
            background="#ffffff",
        ),
        _element(
            "kz_logo_right",
            "image",
            334,
            3,
            81,
            18,
            optional=True,
            logo_role="customer",
            mode="fit",
            opacity=1.0,
            frame=True,
            frame_color="#64748b",
            background="#f8fafc",
            placeholder_text_ru="Загрузить логотип заказчика",
            placeholder_text_kk="Тапсырыс беруші логотипін жүктеу",
            placeholder_text_en="Load customer logo",
            placeholder_font_size_mm=2.2,
        ),
        _element(
            "kz_country_label",
            "text",
            5,
            23,
            25,
            5,
            text="СТРАНА",
            font_size_mm=2.2,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_country",
            "field",
            30,
            23,
            48,
            5,
            field="header.country",
            font_size_mm=2.5,
            frame=True,
        ),
        _element(
            "kz_region_label",
            "text",
            5,
            29,
            25,
            5,
            text="ОБЛАСТЬ",
            font_size_mm=2.2,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_region", "field", 30, 29, 48, 5, field="header.region", font_size_mm=2.5, frame=True
        ),
        _element(
            "kz_district_label",
            "text",
            5,
            35,
            25,
            5,
            text="РАЙОН / УЧАСТОК",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_district",
            "field",
            30,
            35,
            48,
            5,
            field="header.district",
            font_size_mm=2.4,
            frame=True,
        ),
        _element(
            "kz_field_label",
            "text",
            5,
            41,
            25,
            5,
            text="МЕСТОРОЖДЕНИЕ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_field", "field", 30, 41, 48, 5, field="header.field", font_size_mm=2.5, frame=True
        ),
        _element(
            "kz_well_label",
            "text",
            5,
            47,
            25,
            6,
            text="СКВАЖИНА",
            font_size_mm=2.1,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_well",
            "field",
            30,
            47,
            48,
            6,
            field="header.well_number",
            font_size_mm=3.0,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_project_label",
            "text",
            81,
            23,
            28,
            5,
            text="ПРОЕКТ",
            font_size_mm=2.1,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_project",
            "field",
            109,
            23,
            76,
            5,
            field="project.name",
            font_size_mm=2.5,
            frame=True,
        ),
        _element(
            "kz_customer_label",
            "text",
            81,
            29,
            28,
            5,
            text="ЗАКАЗЧИК",
            font_size_mm=2.0,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_customer",
            "field",
            109,
            29,
            76,
            5,
            field="header.customer",
            font_size_mm=2.5,
            frame=True,
        ),
        _element(
            "kz_contractor_label",
            "text",
            81,
            35,
            28,
            5,
            text="ИСПОЛНИТЕЛЬ",
            font_size_mm=1.9,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_contractor",
            "field",
            109,
            35,
            76,
            5,
            field="header.contractor",
            font_size_mm=2.5,
            frame=True,
        ),
        _element(
            "kz_driller_label",
            "text",
            81,
            41,
            28,
            5,
            text="БУРОВАЯ КОМПАНИЯ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_driller",
            "field",
            109,
            41,
            76,
            5,
            field="header.drilling_company",
            font_size_mm=2.4,
            frame=True,
        ),
        _element(
            "kz_target_label",
            "text",
            81,
            47,
            28,
            6,
            text="ЦЕЛЕВОЙ ГОРИЗОНТ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_target",
            "field",
            109,
            47,
            76,
            6,
            field="header.target",
            font_size_mm=2.5,
            frame=True,
        ),
        _element(
            "kz_interval_label",
            "text",
            188,
            23,
            27,
            5,
            text="ИНТЕРВАЛ",
            font_size_mm=2.0,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_interval",
            "field",
            215,
            23,
            54,
            5,
            field="header.interval",
            font_size_mm=2.5,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_scale_label",
            "text",
            188,
            29,
            27,
            5,
            text="МАСШТАБ",
            font_size_mm=2.0,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_scale",
            "field",
            215,
            29,
            54,
            5,
            field="header.scale",
            font_size_mm=2.5,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_rig_label",
            "text",
            188,
            35,
            27,
            5,
            text="БУРОВАЯ",
            font_size_mm=2.0,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_rig", "field", 215, 35, 54, 5, field="header.rig", font_size_mm=2.4, frame=True
        ),
        _element(
            "kz_well_type_label",
            "text",
            188,
            41,
            27,
            5,
            text="ВИД СКВАЖИНЫ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_well_type",
            "field",
            215,
            41,
            54,
            5,
            field="header.well_type",
            font_size_mm=2.4,
            frame=True,
        ),
        _element(
            "kz_engineers_label",
            "text",
            188,
            47,
            27,
            6,
            text="ИНЖЕНЕРЫ / ГЕОЛОГИ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_engineers",
            "field",
            215,
            47,
            54,
            6,
            field="header.engineers",
            font_size_mm=2.2,
            frame=True,
        ),
        _element(
            "kz_actual_label",
            "text",
            272,
            23,
            37,
            5,
            text="ФАКТИЧЕСКАЯ ГЛУБИНА",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_actual",
            "field",
            309,
            23,
            40,
            5,
            field="header.actual_depth",
            font_size_mm=2.4,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_project_depth_label",
            "text",
            272,
            29,
            37,
            5,
            text="ПРОЕКТНАЯ ГЛУБИНА",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_project_depth",
            "field",
            309,
            29,
            40,
            5,
            field="header.project_depth",
            font_size_mm=2.4,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_start_label",
            "text",
            272,
            35,
            37,
            5,
            text="НАЧАЛО БУРЕНИЯ",
            font_size_mm=1.85,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_start",
            "field",
            309,
            35,
            40,
            5,
            field="header.start_date",
            font_size_mm=2.3,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_end_label",
            "text",
            272,
            41,
            37,
            5,
            text="КОНЕЦ БУРЕНИЯ",
            font_size_mm=1.85,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_end",
            "field",
            309,
            41,
            40,
            5,
            field="header.end_date",
            font_size_mm=2.3,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_rig_floor_label",
            "text",
            272,
            47,
            37,
            6,
            text="ВЫСОТА РОТОРА / АЛЬТИТУДА",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_rig_floor",
            "field",
            309,
            47,
            40,
            6,
            field="header.rig_floor",
            font_size_mm=2.2,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_lat_label",
            "text",
            352,
            23,
            22,
            5,
            text="ШИРОТА",
            font_size_mm=1.9,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_lat", "field", 374, 23, 41, 5, field="header.latitude", font_size_mm=2.2, frame=True
        ),
        _element(
            "kz_lon_label",
            "text",
            352,
            29,
            22,
            5,
            text="ДОЛГОТА",
            font_size_mm=1.9,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_lon",
            "field",
            374,
            29,
            41,
            5,
            field="header.longitude",
            font_size_mm=2.2,
            frame=True,
        ),
        _element(
            "kz_rep_label",
            "text",
            352,
            35,
            22,
            5,
            text="ПРЕДСТАВИТЕЛЬ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_rep",
            "field",
            374,
            35,
            41,
            5,
            field="header.customer_representative",
            font_size_mm=2.0,
            frame=True,
        ),
        _element(
            "kz_dataset_label",
            "text",
            352,
            41,
            22,
            5,
            text="ФАЙЛ LAS",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_dataset",
            "field",
            374,
            41,
            41,
            5,
            field="dataset.source_name",
            font_size_mm=1.9,
            frame=True,
        ),
        _element(
            "kz_samples_label",
            "text",
            352,
            47,
            22,
            6,
            text="ОТСЧЁТЫ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
            alignment="center",
        ),
        _element(
            "kz_samples",
            "field",
            374,
            47,
            41,
            6,
            field="dataset.sample_count",
            font_size_mm=2.2,
            frame=True,
            alignment="center",
        ),
        _element("kz_separator", "line", 5, 55, 410, 0.1, color="#334155", width=0.6),
        _element(
            "kz_lithology_legend",
            "lithology_legend",
            5,
            58,
            157,
            42,
            scope="used_manual",
            columns=4,
            show_code=True,
            font_size_mm=1.85,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "kz_lba_legend",
            "lba_legend",
            165,
            58,
            77,
            42,
            font_size_mm=1.8,
            color="#0f172a",
            frame=True,
        ),
        _element(
            "kz_symbols",
            "text",
            245,
            58,
            74,
            42,
            text="УСЛОВНЫЕ ОБОЗНАЧЕНИЯ\n● Фоновый газ\n◆ Газ пластовый\n▲ Газ СПО\n■ Газ-тест\n○ Нефтепроявление\n◉ Нефтенасыщенность\n✦ Керн с признаками УВ",
            font_size_mm=1.85,
            color="#0f172a",
            bold=True,
            frame=True,
            alignment="left",
            text_position="top",
        ),
        _element(
            "kz_construction",
            "field",
            322,
            58,
            93,
            42,
            field="header.well_construction",
            font_size_mm=1.8,
            color="#0f172a",
            frame=True,
            alignment="left",
            text_position="top",
        ),
    ),
)


DAILY_TECHNOLOGY_HEADER = MasterlogHeaderPreset(
    "daily_technology_control",
    _texts(
        "Суточная диаграмма — технологический контроль",
        "Тәуліктік диаграмма — технологиялық бақылау",
        "Daily diagram — technology control",
    ),
    _texts(
        "Готовая оперативная шапка по образцам GeoSketch: два логотипа, интервал, скважина, заказчик, исполнитель и сменный персонал.",
        "GeoSketch үлгілері бойынша дайын жедел тақырып: екі логотип, аралық, ұңғыма, тапсырыс беруші, орындаушы және ауысым персоналы.",
        "Print-ready operational header based on GeoSketch samples with two logos, interval, well, customer, contractor and shift personnel.",
    ),
    50.0,
    (
        _element(
            "daily_logo_contractor",
            "image",
            5,
            2,
            42,
            11,
            optional=True,
            logo_role="contractor",
            mode="fit",
            frame=True,
            placeholder_text_ru="Логотип исполнителя",
            placeholder_text_kk="Орындаушы логотипі",
            placeholder_text_en="Contractor logo",
        ),
        _element(
            "daily_title",
            "text",
            70,
            2,
            145,
            8,
            text="ТЕХНОЛОГИЧЕСКИЙ КОНТРОЛЬ",
            font_size_mm=5.2,
            bold=True,
            alignment="center",
            frame=True,
        ),
        _element(
            "daily_logo_customer",
            "image",
            238,
            2,
            42,
            11,
            optional=True,
            logo_role="customer",
            mode="fit",
            frame=True,
            placeholder_text_ru="Логотип заказчика",
            placeholder_text_kk="Тапсырыс беруші логотипі",
            placeholder_text_en="Customer logo",
        ),
        _element(
            "daily_country_label",
            "text",
            5,
            15,
            24,
            5,
            text="СТРАНА",
            font_size_mm=2.0,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_country",
            "field",
            29,
            15,
            48,
            5,
            field="header.country",
            font_size_mm=2.5,
            frame=True,
        ),
        _element(
            "daily_field_label",
            "text",
            5,
            21,
            24,
            5,
            text="МЕСТОРОЖДЕНИЕ",
            font_size_mm=1.7,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_field",
            "field",
            29,
            21,
            48,
            5,
            field="header.field",
            font_size_mm=2.4,
            frame=True,
        ),
        _element(
            "daily_well_label",
            "text",
            5,
            27,
            24,
            6,
            text="СКВАЖИНА",
            font_size_mm=2.0,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_well",
            "field",
            29,
            27,
            48,
            6,
            field="header.well_number",
            font_size_mm=2.8,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_customer_label",
            "text",
            80,
            15,
            27,
            5,
            text="ЗАКАЗЧИК",
            font_size_mm=1.9,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_customer",
            "field",
            107,
            15,
            69,
            5,
            field="header.customer",
            font_size_mm=2.4,
            frame=True,
        ),
        _element(
            "daily_contractor_label",
            "text",
            80,
            21,
            27,
            5,
            text="ИСПОЛНИТЕЛЬ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_contractor",
            "field",
            107,
            21,
            69,
            5,
            field="header.contractor",
            font_size_mm=2.4,
            frame=True,
        ),
        _element(
            "daily_station_label",
            "text",
            80,
            27,
            27,
            6,
            text="СТАНЦИЯ / ПАРТИЯ",
            font_size_mm=1.7,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_station",
            "field",
            107,
            27,
            69,
            6,
            field="header.rig",
            font_size_mm=2.4,
            frame=True,
        ),
        _element(
            "daily_interval_label",
            "text",
            179,
            15,
            31,
            5,
            text="ИНТЕРВАЛ",
            font_size_mm=1.9,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_interval",
            "field",
            210,
            15,
            70,
            5,
            field="header.interval",
            font_size_mm=2.4,
            frame=True,
            alignment="center",
        ),
        _element(
            "daily_start_label",
            "text",
            179,
            21,
            31,
            5,
            text="НАЧАЛО",
            font_size_mm=1.9,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_start",
            "field",
            210,
            21,
            70,
            5,
            field="header.start_date",
            font_size_mm=2.3,
            frame=True,
            alignment="center",
        ),
        _element(
            "daily_shift_label",
            "text",
            179,
            27,
            31,
            6,
            text="СМЕНА",
            font_size_mm=1.9,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_shift",
            "field",
            210,
            27,
            70,
            12,
            field="header.shift_personnel",
            font_size_mm=2.1,
            frame=True,
            text_position="top",
        ),
        _element(
            "daily_engineers_label",
            "text",
            5,
            36,
            47,
            6,
            text="ИНЖЕНЕРЫ / ГЕОЛОГИ",
            font_size_mm=1.8,
            bold=True,
            frame=True,
        ),
        _element(
            "daily_engineers",
            "field",
            52,
            36,
            124,
            6,
            field="header.engineers",
            font_size_mm=2.2,
            frame=True,
        ),
        _element(
            "daily_notes",
            "field",
            179,
            40,
            101,
            6,
            field="header.notes",
            font_size_mm=2.0,
            frame=True,
        ),
    ),
)


TECHNOLOGY_RESEARCH_HEADER = MasterlogHeaderPreset(
    "technology_research",
    _texts(
        "Технологические исследования",
        "Технологиялық зерттеулер",
        "Technology research",
    ),
    _texts(
        "Расширенная альбомная шапка для глубинных и временных технологических форм с литологической легендой и конструкцией скважины.",
        "Литологиялық шартты белгілер мен ұңғыма конструкциясы бар тереңдік және уақыт технологиялық нысандарына арналған кеңейтілген альбомдық тақырып.",
        "Extended landscape header for depth and time technology forms with lithology legend and well construction.",
    ),
    105.0,
    tuple(deepcopy(DAILY_TECHNOLOGY_HEADER.elements))
    + (
        _element("technology_separator", "line", 5, 48, 275, 0.1, color="#334155", width=0.5),
        _element(
            "technology_lithology",
            "lithology_legend",
            5,
            51,
            135,
            49,
            scope="used_manual",
            columns=4,
            show_code=True,
            font_size_mm=1.9,
            frame=True,
        ),
        _element(
            "technology_symbols",
            "text",
            143,
            51,
            55,
            49,
            text="УСЛОВНЫЕ ОБОЗНАЧЕНИЯ\n● Фоновый газ\n◆ Газ пластовый\n▲ Газ СПО\n■ Газ-тест\n○ Нефтепроявление",
            font_size_mm=1.9,
            bold=True,
            frame=True,
            text_position="top",
        ),
        _element(
            "technology_construction",
            "field",
            201,
            51,
            79,
            49,
            field="header.well_construction",
            font_size_mm=1.9,
            frame=True,
            text_position="top",
        ),
    ),
)


EMERGENCY_CONTROL_HEADER = MasterlogHeaderPreset(
    "emergency_control",
    _texts(
        "Аварийная диаграмма — компактная",
        "Апаттық диаграмма — ықшам",
        "Emergency diagram — compact",
    ),
    _texts(
        "Компактная оперативная шапка для аварийных и коротких временных распечаток.",
        "Апаттық және қысқа уақыттық басылымдарға арналған ықшам жедел тақырып.",
        "Compact operational header for emergency and short time-print jobs.",
    ),
    32.0,
    (
        _element(
            "emergency_logo",
            "image",
            5,
            2,
            39,
            9,
            optional=True,
            logo_role="contractor",
            mode="fit",
            frame=True,
            placeholder_text_ru="Логотип",
            placeholder_text_kk="Логотип",
            placeholder_text_en="Logo",
        ),
        _element(
            "emergency_title",
            "text",
            65,
            2,
            145,
            8,
            text="ТЕХНОЛОГИЧЕСКИЙ КОНТРОЛЬ",
            font_size_mm=4.8,
            bold=True,
            alignment="center",
            frame=True,
        ),
        _element(
            "emergency_interval_label",
            "text",
            65,
            11,
            38,
            5,
            text="ИНТЕРВАЛ",
            font_size_mm=1.9,
            bold=True,
            frame=True,
        ),
        _element(
            "emergency_interval",
            "field",
            103,
            11,
            107,
            5,
            field="header.interval",
            font_size_mm=2.4,
            frame=True,
            alignment="center",
        ),
        _element(
            "emergency_country",
            "field",
            5,
            18,
            50,
            5,
            field="header.country",
            font_size_mm=2.2,
            frame=True,
        ),
        _element(
            "emergency_field",
            "field",
            56,
            18,
            64,
            5,
            field="header.field",
            font_size_mm=2.2,
            frame=True,
        ),
        _element(
            "emergency_well",
            "field",
            121,
            18,
            39,
            5,
            field="header.well_number",
            font_size_mm=2.5,
            bold=True,
            frame=True,
        ),
        _element(
            "emergency_contractor",
            "field",
            161,
            18,
            70,
            5,
            field="header.contractor",
            font_size_mm=2.2,
            frame=True,
        ),
        _element(
            "emergency_rig",
            "field",
            232,
            18,
            48,
            5,
            field="header.rig",
            font_size_mm=2.2,
            frame=True,
        ),
        _element(
            "emergency_engineers",
            "field",
            5,
            24,
            155,
            5,
            field="header.engineers",
            font_size_mm=2.1,
            frame=True,
        ),
        _element(
            "emergency_notes",
            "field",
            161,
            24,
            119,
            5,
            field="header.notes",
            font_size_mm=2.0,
            frame=True,
        ),
    ),
)


COMPACT_HEADER = MasterlogHeaderPreset(
    "compact",
    _texts("Компактная", "Ықшам", "Compact"),
    _texts(
        "Низкая шапка для длинного разреза.",
        "Ұзын қимаға арналған ықшам тақырып.",
        "Low header for long sections.",
    ),
    25.0,
    (
        _element("title", "text", 5, 3, 55, 7, text="MASTERLOG", font_size_mm=5.0, color="#0f172a"),
        _element(
            "project",
            "field",
            62,
            3,
            65,
            7,
            field="project.name",
            font_size_mm=3.5,
            color="#0f172a",
        ),
        _element(
            "well", "field", 130, 3, 75, 7, field="well.name", font_size_mm=3.5, color="#0f172a"
        ),
        _element(
            "dataset",
            "field",
            5,
            13,
            100,
            6,
            field="dataset.name",
            font_size_mm=3.2,
            color="#334155",
        ),
        _element(
            "rig",
            "text",
            110,
            13,
            95,
            6,
            text="Rig / Unit: [edit]",
            font_size_mm=3.2,
            color="#334155",
        ),
    ),
)


def _a4_profile_header(
    profile_id: str,
    profile_names: dict[AppLanguage, str],
    *,
    title: str,
    orientation: str,
) -> MasterlogHeaderPreset:
    """Build one restrained A4 header whose geometry matches its orientation."""

    if orientation not in {"portrait", "landscape"}:
        raise ValueError("A4 header orientation must be portrait or landscape")
    page_width = 210.0 if orientation == "portrait" else 297.0
    margin = 5.0
    gap = 2.0
    usable = page_width - margin * 2.0
    group_width = (usable - gap * 2.0) / 3.0
    label_width = min(26.0, group_width * 0.40)
    height = 34.0
    elements: list[MasterlogHeaderElement] = [
        _element(
            f"{profile_id}_{orientation}_title",
            "text",
            margin,
            2.0,
            usable,
            6.5,
            text=title,
            font_size_mm=4.6,
            bold=False,
            alignment="center",
            frame=True,
            background="#e2e8f0",
            color="#0f172a",
        )
    ]
    rows = (
        (
            ("ПРОЕКТ", "project.name"),
            ("СКВАЖИНА", "well.name"),
            ("ИНТЕРВАЛ", "header.interval"),
        ),
        (
            ("ЗАКАЗЧИК", "header.customer"),
            ("ИСПОЛНИТЕЛЬ", "header.contractor"),
            ("БУРОВАЯ", "header.rig"),
        ),
        (
            ("ФАЙЛ", "dataset.source_name"),
            ("СПЕЦИАЛИСТЫ", "header.engineers"),
            ("МАСШТАБ", "header.scale"),
        ),
    )
    for row_index, row in enumerate(rows):
        y = 10.0 + row_index * 7.0
        for column_index, (label, field_name) in enumerate(row):
            x = margin + column_index * (group_width + gap)
            element_prefix = f"{profile_id}_{orientation}_{row_index}_{column_index}"
            elements.extend(
                (
                    _element(
                        f"{element_prefix}_label",
                        "text",
                        x,
                        y,
                        label_width,
                        5.5,
                        text=label,
                        font_size_mm=1.8,
                        bold=False,
                        alignment="center",
                        word_wrap=False,
                        frame=True,
                        background="#f8fafc",
                        color="#334155",
                    ),
                    _element(
                        f"{element_prefix}_field",
                        "field",
                        x + label_width,
                        y,
                        group_width - label_width,
                        5.5,
                        field=field_name,
                        font_size_mm=2.2,
                        frame=True,
                        color="#0f172a",
                        missing_text="",
                    ),
                )
            )
    orientation_names = {
        "portrait": _texts("книжная", "кітаптық", "portrait"),
        "landscape": _texts("альбомная", "альбомдық", "landscape"),
    }[orientation]
    names = {
        language: f"{profile_names[language]} — A4, {orientation_names[language]}"
        for language in AppLanguage
    }
    descriptions = {
        AppLanguage.RU: (
            "Автоматически согласованная шапка для выбранной формы колонок; "
            f"A4, {orientation_names[AppLanguage.RU]}."
        ),
        AppLanguage.KK: (
            "Таңдалған баған пішінімен автоматты түрде келісілген тақырып; "
            f"A4, {orientation_names[AppLanguage.KK]}."
        ),
        AppLanguage.EN: (
            "Automatically paired header for the selected column form; "
            f"A4 {orientation_names[AppLanguage.EN]}."
        ),
    }
    return MasterlogHeaderPreset(
        f"a4_{profile_id}_{orientation}",
        names,
        descriptions,
        height,
        tuple(elements),
        orientation,
    )


_A4_HEADER_PROFILES = (
    (
        "geology_technology_gas",
        _texts(
            "Геология + технология + газ",
            "Геология + технология + газ",
            "Geology + drilling + gas",
        ),
        "ГЕОЛОГИЯ · ТЕХНОЛОГИЯ · ГАЗ",
    ),
    (
        "technology",
        _texts("Технология", "Технология", "Technology"),
        "ТЕХНОЛОГИЧЕСКИЕ ПАРАМЕТРЫ БУРЕНИЯ",
    ),
    (
        "gas_interpretation",
        _texts(
            "Gas Ratio + Pixler + нормализованный газ",
            "Gas Ratio + Pixler + нормаланған газ",
            "Gas Ratio + Pixler + normalized gas",
        ),
        "GAS RATIO · PIXLER · НОРМАЛИЗОВАННЫЙ ГАЗ",
    ),
    (
        "geology_lab",
        _texts(
            "Геология + шлам + ЛБА + кальциметрия",
            "Геология + шлам + ЛБА + кальциметрия",
            "Geology + cuttings + LBA + calcimetry",
        ),
        "ГЕОЛОГИЯ · ШЛАМ · ЛБА · КАЛЬЦИМЕТРИЯ",
    ),
    (
        "operational_control",
        _texts(
            "Оперативный контроль бурения",
            "Бұрғылауды жедел бақылау",
            "Operational drilling control",
        ),
        "ОПЕРАТИВНЫЙ КОНТРОЛЬ БУРЕНИЯ",
    ),
)

CURATED_MASTERLOG_HEADER_PRESETS = tuple(
    _a4_profile_header(profile_id, names, title=title, orientation=orientation)
    for profile_id, names, title in _A4_HEADER_PROFILES
    for orientation in ("portrait", "landscape")
)

LEGACY_MASTERLOG_HEADER_PRESETS = (
    STANDARD_HEADER,
    LITHOLOGY_HEADER,
    GEOLOGICAL_GEOCHEMICAL_HEADER,
    KAZGEOLOGY_REFERENCE_HEADER,
    DAILY_TECHNOLOGY_HEADER,
    TECHNOLOGY_RESEARCH_HEADER,
    EMERGENCY_CONTROL_HEADER,
    COMPACT_HEADER,
)

BUILTIN_MASTERLOG_HEADER_PRESETS = (
    LEGACY_MASTERLOG_HEADER_PRESETS + CURATED_MASTERLOG_HEADER_PRESETS
)


def _columns(
    *items: tuple[str, str, str, float, list[str], str, float | None, float | None],
) -> list[MasterlogColumnTemplate]:
    palette = ("#2563eb", "#dc2626", "#16a34a", "#9333ea", "#ea580c", "#0891b2")
    columns: list[MasterlogColumnTemplate] = []
    for column_id, title, column_type, width, curves, scale, x_min, x_max in items:
        styles = {
            mnemonic: MasterlogCurveStyle(
                palette[index % len(palette)],
                1.5,
                "solid",
                x_min,
                x_max,
            )
            for index, mnemonic in enumerate(curves)
        }
        columns.append(
            MasterlogColumnTemplate(
                column_id,
                title,
                column_type,
                width,
                curves,
                x_scale=scale,
                x_min=x_min,
                x_max=x_max,
                curve_styles=styles,
                grid_x=bool(curves),
                grid_y=bool(curves),
                grid_major_divisions=5,
                grid_minor_divisions=5,
                grid_alpha=0.22,
            )
        )
    return columns


def _reference_drilling_column() -> MasterlogColumnTemplate:
    curves = ["WOB", "ROP", "DMC", "DEXP"]
    return MasterlogColumnTemplate(
        "drilling_geotech",
        "Нагрузка / скорость проходки / D-экспонента",
        "curves",
        58.0,
        curves,
        x_scale="linear",
        show_legend=True,
        curve_styles={
            "WOB": MasterlogCurveStyle("#2563eb", 1.4, "solid", 0.0, 20.0),
            "ROP": MasterlogCurveStyle("#dc2626", 1.3, "solid", 0.0, 100.0),
            "DMC": MasterlogCurveStyle("#ef4444", 1.0, "dash", 0.0, 50.0),
            "DEXP": MasterlogCurveStyle("#7c3aed", 1.4, "solid", 0.0, 3.0),
        },
        grid_x=True,
        grid_y=True,
        grid_major_divisions=5,
        grid_minor_divisions=5,
        grid_alpha=0.24,
    )


def _reference_gas_column() -> MasterlogColumnTemplate:
    curves = ["C1", "C2", "C3", "C4", "IC4", "C5", "IC5", "TG"]
    palette = (
        "#dc2626",
        "#84cc16",
        "#22d3ee",
        "#fb923c",
        "#65a30d",
        "#9333ea",
        "#d946ef",
        "#ef4444",
    )
    return MasterlogColumnTemplate(
        "component_gas",
        "Газовые компоненты C1-C5 и сумма газов",
        "curves",
        72.0,
        curves,
        x_scale="linear",
        x_min=0.0,
        x_max=100.0,
        show_legend=True,
        curve_styles={
            mnemonic: MasterlogCurveStyle(color, 1.25, "solid", 0.0, 100.0)
            for mnemonic, color in zip(curves, palette, strict=True)
        },
        grid_x=True,
        grid_y=True,
        grid_major_divisions=5,
        grid_minor_divisions=10,
        grid_alpha=0.23,
    )


def _kazgeology_reference_columns() -> list[MasterlogColumnTemplate]:
    return [
        MasterlogColumnTemplate(
            "stratigraphy",
            "Стратиграфия",
            "stratigraphy",
            18.0,
            properties={"title_orientation": "vertical_bottom_to_top", "title_position": "center"},
        ),
        _reference_drilling_column(),
        MasterlogColumnTemplate("depth", "Глубина, м", "depth", 15.0),
        MasterlogColumnTemplate("cuttings", "Шламограмма, %", "cuttings", 31.0),
        MasterlogColumnTemplate("lba", "ЛБА", "lba", 22.0),
        MasterlogColumnTemplate(
            "calcimetry",
            "Карбонатность / кальциметрия, %",
            "calcimetry",
            27.0,
            ["CACO3", "CAMG_CO3_2", "INSOLUBLE"],
            x_scale="linear",
            x_min=0.0,
            x_max=100.0,
            show_legend=True,
            curve_styles={
                "CACO3": MasterlogCurveStyle("#06b6d4", 1.4, "solid", 0.0, 100.0),
                "CAMG_CO3_2": MasterlogCurveStyle("#8b5cf6", 1.4, "solid", 0.0, 100.0),
                "INSOLUBLE": MasterlogCurveStyle("#94a3b8", 1.2, "solid", 0.0, 100.0),
            },
            grid_x=True,
            grid_y=True,
            grid_major_divisions=5,
            grid_minor_divisions=5,
            grid_alpha=0.22,
        ),
        MasterlogColumnTemplate("lithology", "Литология", "lithology", 28.0),
        _reference_gas_column(),
        MasterlogColumnTemplate(
            "description",
            "Описание пород и шлама",
            "cuttings_description",
            125.0,
            properties={"automatic_lithology_fallback": False},
        ),
    ]


BUILTIN_MASTERLOG_FORM_PRESETS = (
    MasterlogFormPreset(
        "kazgeology_reference_blank",
        _texts(
            "МАСТЕРЛОГ — эталонная шапка и глубинная форма",
            "МАСТЕРЛОГ — эталондық тақырып және тереңдік пішіні",
            "MASTERLOG — reference header and depth form",
        ),
        _texts(
            "Рекомендуемый заводской шаблон по переданному образцу: редактируемые реквизиты, две заменяемые зоны логотипов, литологическая легенда, ЛБА, условные обозначения, цветные шкалы и глубинная форма.",
            "Берілген үлгі бойынша пішін: екі жүктелетін логотип аймағы, дайын тақырып, түрлі түсті қисық шкалалары, геология, газ және жыныстардың қолмен сипаттамасы.",
            "Reference-based form with two uploadable logo areas, complete header, coloured curve scales, geology, gas and manual rock descriptions.",
        ),
        MasterlogTemplate(
            "preset:kazgeology_reference_blank",
            "Геолого-технологические исследования — бланк",
            page_format="A3",
            depth_scale=500,
            header_height_mm=KAZGEOLOGY_REFERENCE_HEADER.height_mm,
            header_elements=list(deepcopy(KAZGEOLOGY_REFERENCE_HEADER.elements)),
            columns=_kazgeology_reference_columns(),
            properties={
                "preset_origin": "kazgeology_reference_blank",
                "orientation": "landscape",
                "editable_columns": True,
                "reference_document": "User-provided geological-technological Masterlog example",
                "logo_placeholders": ["kz_logo_left", "kz_logo_right"],
                "description_mode": "manual_only",
            },
        ),
    ),
    MasterlogFormPreset(
        "geological_geochemical_reference",
        _texts(
            "Геолого-геохимический Masterlog",
            "Геологиялық-геохимиялық Masterlog",
            "Geological-geochemical Masterlog",
        ),
        _texts(
            "Рабочая форма по образцу: стратиграфия, бурение, глубина, шламограмма, ЛБА, кальциметрия, литология, газ и описание пород.",
            "Үлгі бойынша жұмыс пішіні: стратиграфия, бұрғылау, тереңдік, шламограмма, ЛБА, кальциметрия, литология, газ және жыныс сипаттамасы.",
            "Reference working layout with stratigraphy, drilling, depth, cuttings, LBA, calcimetry, lithology, gas and rock description.",
        ),
        MasterlogTemplate(
            "preset:geological_geochemical_reference",
            "Geological-geochemical Masterlog",
            header_height_mm=GEOLOGICAL_GEOCHEMICAL_HEADER.height_mm,
            header_elements=list(deepcopy(GEOLOGICAL_GEOCHEMICAL_HEADER.elements)),
            columns=[
                MasterlogColumnTemplate("stratigraphy", "Стратиграфия", "stratigraphy", 20.0),
                _reference_drilling_column(),
                MasterlogColumnTemplate("depth", "Глубина, м", "depth", 14.0),
                MasterlogColumnTemplate("cuttings", "Шламограмма, %", "cuttings", 34.0),
                MasterlogColumnTemplate("lba", "ЛБА", "lba", 24.0),
                MasterlogColumnTemplate(
                    "calcimetry",
                    "Карбонатность / кальциметрия, %",
                    "calcimetry",
                    28.0,
                    ["CACO3", "CAMG_CO3_2"],
                    x_scale="linear",
                    x_min=0.0,
                    x_max=100.0,
                    show_legend=True,
                    curve_styles={
                        "CACO3": MasterlogCurveStyle("#06b6d4", 1.4, "solid", 0.0, 100.0),
                        "CAMG_CO3_2": MasterlogCurveStyle("#8b5cf6", 1.4, "solid", 0.0, 100.0),
                    },
                    grid_x=True,
                    grid_y=True,
                    grid_major_divisions=5,
                    grid_minor_divisions=5,
                    grid_alpha=0.2,
                ),
                MasterlogColumnTemplate("lithology", "Литология", "lithology", 34.0),
                _reference_gas_column(),
                MasterlogColumnTemplate(
                    "description", "Описание пород и шлама", "cuttings_description", 112.0
                ),
            ],
            properties={
                "preset_origin": "geological_geochemical_reference",
                "orientation": "landscape",
                "reference_document": "Anonymized geological-geochemical Masterlog reference",
                "editable_columns": True,
            },
        ),
    ),
    MasterlogFormPreset(
        "international_mudlog",
        _texts("Полевой Masterlog", "Далалық Masterlog", "Field Masterlog"),
        _texts(
            "Нейтральный отраслевой образец: бурение, литология, газ и описание.",
            "Бұрғылау, литология, газ және сипаттамасы бар бейтарап салалық үлгі.",
            "Neutral industry layout for drilling, lithology, gas and descriptions.",
        ),
        MasterlogTemplate(
            "preset:international_mudlog",
            "Field Masterlog",
            header_height_mm=LITHOLOGY_HEADER.height_mm,
            header_elements=list(deepcopy(LITHOLOGY_HEADER.elements)),
            columns=_columns(
                (
                    "drilling",
                    "Drilling parameters: ROP / WOB / TORQUE / GR",
                    "curves",
                    42,
                    ["ROP", "WOB", "TORQUE", "GR"],
                    "linear",
                    0,
                    200,
                ),
                ("depth", "Depth", "depth", 14, [], "linear", None, None),
                (
                    "core_slide",
                    "Core / slide interval",
                    "curves",
                    18,
                    ["CORE_FLAG", "SLIDE_FLAG"],
                    "linear",
                    0,
                    1,
                ),
                ("cuttings", "Cuttings %", "cuttings", 32, [], "linear", None, None),
                (
                    "direct_fluorescence",
                    "Direct fluorescence",
                    "curves",
                    18,
                    ["DIR_FLUOR"],
                    "linear",
                    0,
                    5,
                ),
                (
                    "cut_fluorescence",
                    "Cut fluorescence",
                    "curves",
                    18,
                    ["CUT_FLUOR"],
                    "linear",
                    0,
                    5,
                ),
                (
                    "resistivity",
                    "ILM / ILD",
                    "curves",
                    42,
                    ["ILM", "ILD"],
                    "linear",
                    0.0,
                    2000,
                ),
                (
                    "gas",
                    "TG / C1 / C2 / C3 / iC4 / nC4 / iC5 / nC5",
                    "curves",
                    62,
                    ["TG", "C1", "C2", "C3", "IC4", "NC4", "IC5", "NC5"],
                    "linear",
                    0,
                    1000000,
                ),
                (
                    "calcimetry",
                    "Total CO₃ / CaCO₃ / MgCO₃",
                    "calcimetry",
                    30,
                    ["CACO3", "CAMG_CO3_2"],
                    "linear",
                    0,
                    100,
                ),
                ("lithology", "Lithology", "lithology", 25, [], "linear", None, None),
                (
                    "interpretation",
                    "Interpretation",
                    "analysis_interpretation",
                    34,
                    [],
                    "linear",
                    None,
                    None,
                ),
                (
                    "description",
                    "Lith description and others",
                    "cuttings_description",
                    72,
                    [],
                    "linear",
                    None,
                    None,
                ),
            ),
            properties={"preset_origin": "international_mudlog", "orientation": "landscape"},
        ),
    ),
    MasterlogFormPreset(
        "gas_evaluation",
        _texts("Газовый Masterlog", "Газдық Masterlog", "Gas evaluation Masterlog"),
        _texts(
            "Форма для компонентного газа и расчётных Gas Ratio.",
            "Компоненттік газ және Gas Ratio есептері үшін пішін.",
            "Layout for component gas and calculated Gas Ratio curves.",
        ),
        MasterlogTemplate(
            "preset:gas_evaluation",
            "Gas evaluation Masterlog",
            header_elements=list(deepcopy(COMPACT_HEADER.elements)),
            header_height_mm=COMPACT_HEADER.height_mm,
            columns=_columns(
                ("depth", "Depth", "depth", 14, [], "linear", None, None),
                (
                    "gas",
                    "Gas components",
                    "curves",
                    70,
                    ["TG", "C1", "C2", "C3", "IC4", "NC4", "IC5", "NC5"],
                    "linear",
                    0,
                    1000000,
                ),
                (
                    "ratios",
                    "Wetness / Balance / Character / Pixler",
                    "curves",
                    55,
                    ["WH", "BH", "CH", "C1_C2", "C1_C3", "C1_C4", "C1_C5"],
                    "linear",
                    0,
                    100,
                ),
                ("lithology", "Lithology", "lithology", 25, [], "linear", None, None),
                ("description", "Description", "text", 46, [], "linear", None, None),
            ),
            properties={"preset_origin": "gas_evaluation", "orientation": "landscape"},
        ),
    ),
    MasterlogFormPreset(
        "geological_description",
        _texts("Геологическое описание", "Геологиялық сипаттама", "Geological description"),
        _texts(
            "Расширенная литологическая колонка и текстовое описание шлама.",
            "Кеңейтілген литологиялық баған және шламның мәтіндік сипаттамасы.",
            "Expanded lithology column and textual cuttings description.",
        ),
        MasterlogTemplate(
            "preset:geological_description",
            "Geological description",
            header_height_mm=LITHOLOGY_HEADER.height_mm,
            header_elements=list(deepcopy(LITHOLOGY_HEADER.elements)),
            columns=_columns(
                ("depth", "Depth", "depth", 14, [], "linear", None, None),
                ("stratigraphy", "Stratigraphy", "stratigraphy", 35, [], "linear", None, None),
                ("drilling", "ROP / GR", "curves", 38, ["ROP", "GR"], "linear", 0, 200),
                ("lithology", "Lithology", "lithology", 38, [], "linear", None, None),
                (
                    "description",
                    "Cuttings / shows / interpretation",
                    "cuttings_description",
                    120,
                    [],
                    "linear",
                    None,
                    None,
                ),
            ),
            properties={"preset_origin": "geological_description", "orientation": "landscape"},
        ),
    ),
)


def _scaled_a4_columns(
    columns: list[MasterlogColumnTemplate], orientation: str
) -> list[MasterlogColumnTemplate]:
    target_width = 200.0 if orientation == "portrait" else 287.0
    result = deepcopy(columns)
    total = sum(column.width_mm for column in result)
    if total <= 0:
        return result
    for column in result:
        column.width_mm = target_width * column.width_mm / total
    return result


_A4_FORM_PROFILE_COLUMNS: dict[str, list[MasterlogColumnTemplate]] = {
    "geology_technology_gas": _columns(
        ("depth", "Depth", "depth", 14, [], "linear", None, None),
        ("stratigraphy", "Stratigraphy", "stratigraphy", 16, [], "linear", None, None),
        (
            "drilling",
            "ROP / WOB / SPP / DEXP",
            "curves",
            34,
            ["ROP", "WOB", "SPP", "DEXP"],
            "linear",
            0,
            250,
        ),
        ("cuttings", "Cuttings", "cuttings", 17, [], "linear", None, None),
        ("lba", "LBA", "lba", 16, [], "linear", None, None),
        ("calcimetry", "Calcimetry", "calcimetry", 24, ["CACO3", "CAMG_CO3_2"], "linear", 0, 100),
        ("lithology", "Lithology", "lithology", 19, [], "linear", None, None),
        (
            "gas",
            "TG / C1-C5",
            "curves",
            42,
            ["TG", "C1", "C2", "C3", "IC4", "NC4", "IC5", "NC5"],
            "linear",
            0,
            100,
        ),
        (
            "description",
            "Rock and cuttings description",
            "cuttings_description",
            46,
            [],
            "linear",
            None,
            None,
        ),
    ),
    "technology": _columns(
        ("depth", "Depth", "depth", 18, [], "linear", None, None),
        (
            "mechanics",
            "ROP / WOB / RPM / TQ / HKLD",
            "curves",
            64,
            ["ROP", "WOB", "RPM", "TQ", "HKLD"],
            "linear",
            0,
            250,
        ),
        (
            "hydraulics",
            "SPP / FLOW IN / FLOW OUT",
            "curves",
            58,
            ["SPP", "FLOW_IN", "FLOW_OUT"],
            "linear",
            0,
            300,
        ),
        (
            "mud",
            "Mud density / temperature",
            "curves",
            48,
            ["MW_IN", "MW_OUT", "TEMP_IN", "TEMP_OUT"],
            "linear",
            0,
            200,
        ),
        ("events", "Operations and comments", "text", 52, [], "linear", None, None),
    ),
    "gas_interpretation": _columns(
        ("depth", "Depth", "depth", 16, [], "linear", None, None),
        (
            "normalized",
            "TG / normalized gas",
            "curves",
            42,
            ["TG", "C1_NORM", "NORMALIZED_TOTAL_GAS", "HC_SUM_NORM"],
            "linear",
            0,
            100,
        ),
        (
            "components",
            "C1-C5",
            "curves",
            52,
            ["C1", "C2", "C3", "IC4", "NC4", "IC5", "NC5"],
            "linear",
            0,
            100,
        ),
        ("gas_ratio", "Wh / Bh / Ch", "curves", 40, ["WH", "BH", "CH"], "linear", 0, 100),
        (
            "pixler",
            "Pixler C1/C2-C5",
            "curves",
            44,
            ["PIXLER_C1_C2", "PIXLER_C1_C3", "PIXLER_C1_C4", "PIXLER_C1_C5"],
            "linear",
            0,
            100,
        ),
        ("dexp", "DEXP / corrected DEXP", "curves", 36, ["DEXP", "D_EXP_CORR"], "linear", 0, 5),
        (
            "interpretation",
            "Interpretation",
            "analysis_interpretation",
            44,
            [],
            "linear",
            None,
            None,
        ),
    ),
    "geology_lab": _columns(
        ("depth", "Depth", "depth", 16, [], "linear", None, None),
        ("stratigraphy", "Stratigraphy", "stratigraphy", 20, [], "linear", None, None),
        ("cuttings", "Cuttings", "cuttings", 24, [], "linear", None, None),
        ("lba", "LBA", "lba", 22, [], "linear", None, None),
        ("calcimetry", "Calcimetry", "calcimetry", 34, ["CACO3", "CAMG_CO3_2"], "linear", 0, 100),
        ("lithology", "Lithology", "lithology", 28, [], "linear", None, None),
        ("gas", "Total gas", "curves", 28, ["TG", "TOTAL_GAS"], "linear", 0, 100),
        (
            "description",
            "Rock and cuttings description",
            "cuttings_description",
            68,
            [],
            "linear",
            None,
            None,
        ),
    ),
    "operational_control": _columns(
        ("depth", "Time / depth", "depth", 18, [], "linear", None, None),
        (
            "drilling",
            "WOB / HKLD / ROP / RPM / TQ",
            "curves",
            60,
            ["WOB", "HKLD", "ROP", "RPM", "TQ"],
            "linear",
            0,
            250,
        ),
        (
            "pumps",
            "SPP / pumps / flow",
            "curves",
            54,
            ["SPP", "SPM1", "SPM2", "FLOW_IN", "FLOW_OUT"],
            "linear",
            0,
            300,
        ),
        ("mud_gas", "Mud / gas", "curves", 48, ["MW_IN", "MW_OUT", "TG", "C1"], "linear", 0, 100),
        (
            "pits",
            "Pit volumes",
            "curves",
            48,
            ["PIT_VOL", "PIT1", "PIT2", "PIT3", "PIT4"],
            "linear",
            0,
            500,
        ),
        ("events", "Operations and comments", "text", 52, [], "linear", None, None),
    ),
}


def _a4_form_preset(
    profile_id: str,
    profile_names: dict[AppLanguage, str],
    *,
    orientation: str,
) -> MasterlogFormPreset:
    header_id = f"a4_{profile_id}_{orientation}"
    header = next(item for item in CURATED_MASTERLOG_HEADER_PRESETS if item.preset_id == header_id)
    orientation_names = {
        "portrait": _texts("книжная", "кітаптық", "portrait"),
        "landscape": _texts("альбомная", "альбомдық", "landscape"),
    }[orientation]
    names = {
        language: f"{profile_names[language]} — A4, {orientation_names[language]}"
        for language in AppLanguage
    }
    descriptions = {
        AppLanguage.RU: "Готовая форма колонок с автоматически согласованной печатной шапкой.",
        AppLanguage.KK: "Автоматты түрде келісілген баспа тақырыбы бар дайын баған пішіні.",
        AppLanguage.EN: "Ready column layout with an automatically paired print header.",
    }
    return MasterlogFormPreset(
        f"a4_{profile_id}_{orientation}",
        names,
        descriptions,
        MasterlogTemplate(
            f"preset:a4_{profile_id}_{orientation}",
            names[AppLanguage.RU],
            page_format="A4",
            depth_scale=500,
            header_height_mm=header.height_mm,
            header_elements=list(deepcopy(header.elements)),
            columns=_scaled_a4_columns(_A4_FORM_PROFILE_COLUMNS[profile_id], orientation),
            properties={
                "preset_origin": f"a4_{profile_id}_{orientation}",
                "print_profile_id": profile_id,
                "paired_header_preset_id": header_id,
                "orientation": orientation,
            },
        ),
    )


CURATED_MASTERLOG_FORM_PRESETS = tuple(
    _a4_form_preset(profile_id, names, orientation=orientation)
    for profile_id, names, _title in _A4_HEADER_PROFILES
    for orientation in ("portrait", "landscape")
)

LEGACY_MASTERLOG_FORM_PRESETS = BUILTIN_MASTERLOG_FORM_PRESETS
BUILTIN_MASTERLOG_FORM_PRESETS = LEGACY_MASTERLOG_FORM_PRESETS + CURATED_MASTERLOG_FORM_PRESETS


def builtin_form_preset(preset_id: str) -> MasterlogFormPreset:
    try:
        return next(item for item in BUILTIN_MASTERLOG_FORM_PRESETS if item.preset_id == preset_id)
    except StopIteration as exc:
        raise KeyError(f"Встроенный образец masterlog не найден: {preset_id}") from exc


def builtin_header_preset(preset_id: str) -> MasterlogHeaderPreset:
    try:
        return next(
            item for item in BUILTIN_MASTERLOG_HEADER_PRESETS if item.preset_id == preset_id
        )
    except StopIteration as exc:
        raise KeyError(f"Встроенный образец шапки не найден: {preset_id}") from exc
